# Generated by Django 4.1 on 2022-09-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('fecha_de_creacion', models.DateField()),
                ('episodios', models.IntegerField()),
                ('temporadas', models.IntegerField()),
                ('origen', models.CharField(max_length=40)),
                ('personaje_principal', models.CharField(max_length=40)),
                ('sinopsis', models.CharField(max_length=2000)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('imagen_del_anime', models.ImageField(upload_to='')),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('bibliografia', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('detalle', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_anime', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
                ('anime', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Final.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Final.autor'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Final.genero'),
        ),
    ]
