# Generated by Django 4.1 on 2022-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Final', '0003_remove_anime_imagen_del_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imagen_del_anime',
            field=models.ImageField(default=123, upload_to='imagenes'),
            preserve_default=False,
        ),
    ]
