# Generated by Django 4.1 on 2022-09-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Final', '0005_alter_anime_imagen_del_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='titulo',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre_editorial',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
