# Generated by Django 4.1 on 2022-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Final', '0007_alter_anime_autor_alter_anime_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre_editorial',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
