# Generated by Django 4.1 on 2022-09-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Final', '0008_alter_anime_titulo_alter_autor_nombre_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
