# Generated by Django 4.1 on 2022-09-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Final', '0009_anime_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='anime',
        ),
        migrations.DeleteModel(
            name='mensaje',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
