# Generated by Django 4.1 on 2022-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Final', '0011_alter_anime_sinopsis_alter_autor_bibliografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='sinopsis',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='autor',
            name='bibliografia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genero',
            name='detalle',
            field=models.CharField(max_length=500),
        ),
    ]
