# Generated by Django 4.1 on 2022-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAppFinal', '0003_rename_avatar_avatar_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatares'),
        ),
    ]
