# Generated by Django 4.1 on 2022-09-25 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAppFinal', '0008_alter_avatar_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=2000)),
                ('asunto', models.CharField(max_length=50)),
                ('enviado', models.DateTimeField(auto_now_add=True)),
                ('envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Envia', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
