# Generated by Django 4.1 on 2022-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAppFinal', '0009_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='imagen_mensaje',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
