# Generated by Django 4.1 on 2022-09-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAppFinal', '0010_mensajes_imagen_mensaje_alter_mensajes_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='imagen_mensaje',
        ),
    ]
