# Generated by Django 4.1 on 2022-09-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAppFinal', '0011_remove_mensajes_imagen_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='asunto',
        ),
    ]
