# Generated by Django 4.1 on 2022-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAppFinal', '0012_remove_mensajes_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.TextField(max_length=40),
        ),
    ]
